# Generated by Django 4.1.1 on 2023-02-16 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Account', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='is_superAdmin',
            field=models.BooleanField(default=False),
        ),
    ]
