# Generated by Django 4.1.1 on 2023-02-13 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='poin',
            field=models.IntegerField(default=0),
        ),
    ]
