# Generated by Django 4.1.1 on 2023-02-13 08:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Account', '0002_user_poin'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='poin',
        ),
    ]
