# Generated by Django 4.1.1 on 2023-02-10 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Account', '0004_alter_account_is_staff'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='name',
            field=models.TextField(blank=True, max_length=32, unique=True),
        ),
    ]
