# Generated by Django 3.2 on 2023-02-11 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Account', '0005_alter_account_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='poin',
            field=models.IntegerField(default=0),
        ),
    ]
