# Generated by Django 4.1.1 on 2023-02-14 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Poin', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='poin',
            name='volume',
            field=models.IntegerField(default=0),
        ),
    ]
