# Generated by Django 3.2.17 on 2023-02-11 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Minyak',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=50)),
                ('id_user', models.IntegerField(null=True)),
                ('email', models.EmailField(max_length=254, null=True)),
                ('phone', models.TextField(max_length=16, null=True)),
                ('volume', models.IntegerField(null=True)),
                ('poin', models.IntegerField(null=True)),
                ('status', models.CharField(default='Menunggu Verifikasi', max_length=50)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
