# Generated by Django 4.1.1 on 2023-02-10 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Minyak', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Poin',
        ),
        migrations.AddField(
            model_name='minyak',
            name='email',
            field=models.EmailField(max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='minyak',
            name='id_user',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='minyak',
            name='phone',
            field=models.TextField(max_length=16, null=True),
        ),
        migrations.AddField(
            model_name='minyak',
            name='poin',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='minyak',
            name='status',
            field=models.CharField(default='Menunggu Verifikasi', max_length=50),
        ),
        migrations.AlterField(
            model_name='minyak',
            name='volume',
            field=models.IntegerField(null=True),
        ),
    ]
