# Generated by Django 3.2.17 on 2023-02-12 03:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Transaction', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaksi',
            name='waktuTransaksi',
            field=models.TextField(default=datetime.date(2023, 2, 12)),
        ),
    ]
