# Generated by Django 3.2 on 2023-02-11 02:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Transaction', '0002_alter_transaksi_waktutransaksi'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaksi',
            name='waktuTransaksi',
            field=models.TextField(default=datetime.date(2023, 2, 11)),
        ),
    ]
