# Generated by Django 3.2 on 2023-02-11 11:04

import API.Produk.models
from django.db import migrations, models
import djongo.models.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Kategori',
            fields=[
                ('_id', djongo.models.fields.ObjectIdField(auto_created=True, primary_key=True, serialize=False)),
                ('nama', models.CharField(max_length=64)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Penukaran',
            fields=[
                ('_id', djongo.models.fields.ObjectIdField(auto_created=True, primary_key=True, serialize=False)),
                ('nama', models.CharField(max_length=128)),
                ('kode', models.CharField(default='xxx', max_length=16)),
                ('email', models.CharField(max_length=128)),
                ('phone', models.CharField(max_length=128)),
                ('produk', models.CharField(max_length=128)),
                ('jumlah', models.IntegerField()),
                ('tanggal', models.DateTimeField()),
                ('selesai', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Produk',
            fields=[
                ('_id', djongo.models.fields.ObjectIdField(auto_created=True, primary_key=True, serialize=False)),
                ('nama', models.CharField(max_length=64)),
                ('stok', models.IntegerField()),
                ('keterangan', models.CharField(max_length=128)),
                ('id_mesin', models.CharField(max_length=128)),
                ('gambar', models.ImageField(blank=True, null=True, upload_to=API.Produk.models.uploadTo)),
                ('harga', models.IntegerField()),
                ('kategori', models.CharField(default='', max_length=200)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
