# Generated by Django 3.2 on 2023-02-11 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Produk', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='penukaran',
            name='biaya',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='produk',
            name='penukar',
            field=models.IntegerField(default=0),
        ),
    ]
