# Generated by Django 3.2 on 2023-02-13 11:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Produk', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='penukaran',
            name='phone',
        ),
    ]
