# Generated by Django 3.2 on 2023-02-11 02:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Produk', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kategori',
            name='created',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='kategori',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
