# Generated by Django 3.2 on 2023-02-11 08:20

import API.Produk.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Produk', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produk',
            name='gambar',
            field=models.ImageField(blank=True, null=True, upload_to=API.Produk.models.uploadTo),
        ),
    ]
