# Generated by Django 3.2 on 2023-02-11 08:23

import API.Produk.models
from django.db import migrations
import djongo.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('Produk', '0002_alter_produk_gambar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produk',
            name='penukaran',
            field=djongo.models.fields.ArrayField(blank=True, default=[], model_container=API.Produk.models.Penukaran, null=True),
        ),
    ]
